### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by oguzdag** [deepfence/PacketStreamer#21]
**Describe the bug**
When i installed packetstreamer to one of our AWS kubernetes clusters using provided helm-chart with receiver.yaml values file (also provided under contrib/config)

I am getting below error on the both receiver and sensor pods

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62b655]

goroutine 1 [running]:
github.com/deepfence/PacketStreamer/pkg/config.NewConfig({0x7ffea2bcfcd5, 0x1f})
        /src/pkg/config/config.go:138 +0x175
github.com/deepfence/PacketStreamer/cmd.initConfig()
        /src/cmd/root.go:46 +0x4d
github.com/spf13/cobra.(*Command).preRun(0xe9f800)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:886 +0x42
github.com/spf13/cobra.(*Command).execute(0xe9f800, {0xc0000d5280, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:822 +0x1db
github.com/spf13/cobra.(*Command).ExecuteC(0xe9f580)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/deepfence/PacketStreamer/cmd.Execute()
        /src/cmd/root.go:28 +0x25
main.main()
        /src/main.go:6 +0x17
        
I didn't change default values file and using this image deepfenceio/deepfence_packetstreamer:latest

**To Reproduce**
helm install to an kubernetes cluster in aws using receiver.yaml values file

**Expected behavior**
was expecting it to work out of box

**Additional context**

**Comment by oguzdag** [comment]
forgot to add kubernetes version 1.21.5

**Comment by noboruma** [comment]
Hello @oguzdag 
Thanks for finding and sharing that bug!
I was able to reproduce and found the issue.
The PR available at: https://github.com/deepfence/PacketStreamer/pull/22

In the meanwhile I have pushed a new (and temporary) docker image with the fix: deepfenceio/deepfence_packetstreamer:fix
Please feel free to use that image until everything gets approved.
