### ISSUE TITLE
request a release

### ISSUE THREAD

**Issue by chenrui333** [deepfence/PacketStreamer#27]
I wonder if there is any release plan down the path.

**Comment by sandman137** [comment]
Hi @chenrui333, we were planning to tag a first release after closing on tickets #1, #3, #4 and #24. Did you have any suggestions/inputs?

**Comment by vadorovsky** [comment]
Is #24 necessary? I would be non-trivial to implement, we would need to somehow support WinPcap and as far as I know there is no ready to use Go library for that, so we would have to write our own from scratch.

**Comment by vadorovsky** [comment]
But I totally agree that we should address the other three issues before releasing.

**Comment by sandman137** [comment]
On #24, all we need to do is provide build instructions for windows.
